# repo-sync.yml
name: sync

on:
  schedule:
  - cron:  "*/30 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: GitHub Repo Sync
      uses: repo-sync/github-sync@v2.3.0
      env:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source_repo: "仓库地址"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.PAT }}
